- descriptor: "pip-services-container:container-info:default:default:1.0"
  name: "pip-services-roles"
  description: "User roles microservice"

- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-roles:persistence:file:default:1.0"
  path: "./data/roles.json"

- descriptor: "pip-services-roles:controller:default:default:1.0"

- descriptor: "pip-services-roles:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 3000
